### ISSUE TITLE
Não processar letras que começam com maiúsculas ou que tenham maiúsculas.

### ISSUE THREAD

**Issue by Pallas1303** [falabrasil/annotator#1]
Olá, eu estou usado o annotator para criação de um léxico com festival para fins de experimentos. Eu notei que ao usar com letras que começam ou tinha maiúsculas, por exemplo usar "Nove, Oi, NIlo" o annotator não considera maiúsculas, as ignorado. E mostar na execução do annotator:

```
[G2P] Error while processing word 'OI', skipping char 'O'. There may be errors at phoneme output
[G2P] Error while processing word 'OI', skipping char 'I'. There may be errors at phoneme output
[G2P] Error while processing word 'Seis', skipping char 'S'. There may be errors at phoneme output
[G2P] Error while processing word 'Neve', skipping char 'N'. There may be errors at phoneme output
[G2P] Error while processing word 'Nove', skipping char 'N'. There may be errors at phoneme output
[VOW] ## stress vowel not found!
[VOW] #NIlo# stress vowel not found!
[G2P] Error while processing word 'NIlo', skipping char 'N'. There may be errors at phoneme output
[G2P] Error while processing word 'NIlo', skipping char 'I'. There may be errors at phoneme output
Arquivo txt salvo
```

Eu não irei usar maiúsculas no processo de criação, mas notei essa característica.

**Comment by cassiotbatista** [comment]
Oi,

Obrigado pela observação.

Acho que esse é o comportamento padrão, mesmo. O G2P espera que o texto tenha sido normalizado de antemão. Caracteres inválidos, como pontuação ou letras não presentes em qualquer palavra nativa em PT_BR, também produzem o mesmo "erro".
