### ISSUE TITLE
Como posso usar a opção --cross em frases sem que a saida seja uma palavra por linha?

### ISSUE THREAD

**Issue by Pallas1303** [falabrasil/annotator#2]
Olá denovo, eu estou usado o Annotator para G2P. Eu estou usado para transcrição fonética de símbolos/emoji que em grande maioria contendo mais de uma palavra para um dicionário fonético. 

Apenas quero a transcrição fonética por causa disso estou a utilizar a opção --cross. Que tem sucesso em palavras. Mas ao usar em frases o resultado não é esperando. Exemplo:

```sh
root@localhost: java -jar fb_nlplib.jar -g "a casa tem duas janelas" -c
Aviso: {v|s|g} não interferem em 'c'
a
k a z a
t e~ j~
d u a s
Z a n E l a s
````

O resultado que estou espero:
```sh
root@localhost: java -jar fb_nlplib.jar -g "a casa tem duas janelas" -c

a k a z a t e~ j~ d u a s Z a n E l a s
```

Como posso fazer que o comando retorne como ao resultado acima? 

Tenha um bom dia! Estarei ansiosa em receber sua resposta.

**Comment by cassiotbatista** [comment]
Oi,

Infelizmente, apenas com o binario nao e' possivel. O que podes tentar e' uma combinacao com alguns comandos nativos do Bash, como o `xargs` por exemplo:

```bash
$ java -jar fb_nlplib.jar -c "a casa tem duas janelas" | xargs
a k a z a t e~ j~ d u a s Z a n E l a s
```

'A titulo de informacao, o annotator forca o retorno de palavras individuais por linha com a opcao `--cross` porque o objetivo da flag e' tratar interacao entre fonemas no inicio e final de palavras vizinhas. No exemplo a seguir, onde a palavras "casa" e "amarela" comecam e terminam com a vogal "a", ocorre um fenomeno chamado de elisao, onde apenas um de dois fonemas identicos permanece, resultando portanto na pronuncia da "casamarela":

```bash
$ java -jar fb_nlplib.jar -c "a casa amarela"                 
a
k a z a m a r E l a
```

**Comment by Pallas1303** [comment]
Muito obrigada! Eu irei usar comandos para tratar a saída do Annotator.
